name: Build a debug deb
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build tweak with the debug mode
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          submodules: true

      - name: Build for rootless
        run: |
          mkdir packages
          touch ./packages/a.txt
          touch ./packages/b.txt
          ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: packages/*
